message(STATUS "StratifyOS CMake")
if(SOS_IS_LINK)
	message(STATUS "Including Stratify OS link Cmake modules")
	set(STRATIFYOS_CMAKE_CONFIG_LIST release debug coverage)
	sos_sdk_include_target(StratifyOS "${STRATIFYOS_CMAKE_CONFIG_LIST}")
else()
	message(STATUS "Including Stratify OS ARM Cmake modules")
	set(STRATIFYOS_CMAKE_CONFIG_LIST release debug)
	sos_sdk_include_target(StratifyOS_mcu "${STRATIFYOS_CMAKE_CONFIG_LIST}")
	sos_sdk_include_target(StratifyOS_linktransport "${STRATIFYOS_CMAKE_CONFIG_LIST}")
	sos_sdk_include_target(StratifyOS_cortexm "${STRATIFYOS_CMAKE_CONFIG_LIST}")
	sos_sdk_include_target(StratifyOS_usbd "${STRATIFYOS_CMAKE_CONFIG_LIST}")
	sos_sdk_include_target(StratifyOS_device "${STRATIFYOS_CMAKE_CONFIG_LIST}")
	sos_sdk_include_target(StratifyOS_sys "${STRATIFYOS_CMAKE_CONFIG_LIST}")
	sos_sdk_include_target(StratifyOS_crt "${STRATIFYOS_CMAKE_CONFIG_LIST}")
	sos_sdk_include_target(StratifyOS_boot "${STRATIFYOS_CMAKE_CONFIG_LIST}")
endif()
