/*
 * stratify_link_transport_common.h
 *
 *  Created on: May 23, 2016
 *      Author: tgil
 */

#ifndef STRATIFY_LINK_TRANSPORT_USB_COMMON_H_
#define STRATIFY_LINK_TRANSPORT_USB_COMMON_H_


#define LINK_USBPHY_BULK_ENDPOINT (0x2)
#define LINK_USBPHY_BULK_ENDPOINT_ALT (0x5)
#define LINK_USBPHY_BULK_ENDPOINT_SIZE (64)
#define USB_PORT 0
#define USB_INTIN 0x81
#define USB_INTIN_ALT 0x84
#define USB_BULKIN (0x80|LINK_USBPHY_BULK_ENDPOINT)
#define USB_BULKOUT (LINK_USBPHY_BULK_ENDPOINT)
#define USB_BULKIN_ALT (0x80|LINK_USBPHY_BULK_ENDPOINT_ALT)
#define USB_BULKOUT_ALT (LINK_USBPHY_BULK_ENDPOINT_ALT)
#define ENDPOINT_SIZE LINK_USBPHY_BULK_ENDPOINT_SIZE


#endif /* STRATIFY_LINK_TRANSPORT_USB_COMMON_H_ */
