
#ifndef CONFIG_SOS_CONFIG_H
#define CONFIG_SOS_CONFIG_H

//PTHREAD CONFIGURATION OPTIONS
#define CONFIG_PTHREAD_MAX_LOCKS 1024
#define CONFIG_PTHREAD_MUTEX_PRIO_CEILING 0
#define CONFIG_PTHREAD_STACK_MIN 128
#define CONFIG_PTHREAD_DEFAULT_STACK_SIZE 1536

//SCHED CONFIGURATION OPTIONS
#define CONFIG_SCHED_LOWEST_PRIORITY 0
#define CONFIG_SCHED_HIGHEST_PRIORITY 31
#define CONFIG_SCHED_DEFAULT_PRIORITY 0
//duration is in milliseconds
#define CONFIG_SCHED_RR_DURATION 10

//Task options
//total number of threads (system and application)
//more tasks use require more sysmem
#define CONFIG_TASK_TOTAL 16
#define CONFIG_TASK_PROCESS_TIMER_COUNT 2
#define CONFIG_TASK_DEFAULT_STACKGUARD_SIZE 128

#define CONFIG_TASK_NUM_SIGNALS 32


#define CONFIG_MALLOC_CHUNK_SIZE 32
#define CONFIG_MALLOC_SBRK_JUMP_SIZE 128



#define CONFIG_USE_STDIO 1



#endif /* CONFIG_SOS_CONFIG_H */

