
# the name of the target operating system

message(STATUS "Set GCC toolchain to gcc")
message(STATUS "Toolchain host " ${TOOLCHAIN_HOST})

if(TOOLCHAIN_DIR)
    message(STATUS "Toolchain directory " ${TOOLCHAIN_DIR})
else()
		set(TOOLCHAIN_DIR /StratifyLabs-SDK/Tools/gcc)
endif()

set(SOS_SDK_LIB_DIR ${TOOLCHAIN_DIR}/../../lib)

set(SDK_DIR ${TOOLCHAIN_DIR})

include(${CMAKE_CURRENT_LIST_DIR}/sos-gcc-toolchain.cmake)

set(TOOLCHAIN_C_FLAGS "-D__linux" CACHE INTERNAL "GCC C FLAGS")
set(TOOLCHAIN_CXX_FLAGS "${TOOLCHAIN_C_FLAGS} -std=c++11" CACHE INTERNAL "GCC CXX FLAGS")

set(CMAKE_INSTALL_PREFIX ${SDK_DIR})
include_directories(SYSTEM ${SDK_DIR}/include)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(CMAKE_C_FLAGS ${TOOLCHAIN_C_FLAGS} CACHE INTERNAL "GCC C FLAGS")
set(CMAKE_CXX_FLAGS ${TOOLCHAIN_CXX_FLAGS} CACHE INTERNAL "GCC CXX FLAGS")
