
if( ${CMAKE_HOST_SYSTEM_NAME} STREQUAL "Darwin" )
	include(link-clang-toolchain)
endif()
if( ${CMAKE_HOST_SYSTEM_NAME} STREQUAL "Windows" )
	include(link-mingw-toolchain)
endif()
if( ${CMAKE_HOST_SYSTEM_NAME} STREQUAL "Linux" )
	include(link-linux-gcc-toolchain)
endif()
