
set(SOS_LIB_ARCH v7m)
include(${SOS_TOOLCHAIN_CMAKE_PATH}/sos-lib.cmake)
set(SOS_LIB_ARCH v7em)
include(${SOS_TOOLCHAIN_CMAKE_PATH}/sos-lib.cmake)
#set(SOS_LIB_ARCH v7em_f4ss)
#include(${SOS_TOOLCHAIN_CMAKE_PATH}/sos-lib.cmake)
set(SOS_LIB_ARCH v7em_f4sh)
include(${SOS_TOOLCHAIN_CMAKE_PATH}/sos-lib.cmake)
#set(SOS_LIB_ARCH v7em_f5ss)
#include(${SOS_TOOLCHAIN_CMAKE_PATH}/sos-lib.cmake)
set(SOS_LIB_ARCH v7em_f5sh)
include(${SOS_TOOLCHAIN_CMAKE_PATH}/sos-lib.cmake)
#set(SOS_LIB_ARCH v7em_f5ds)
#include(${SOS_TOOLCHAIN_CMAKE_PATH}/sos-lib.cmake)
set(SOS_LIB_ARCH v7em_f5dh)
include(${SOS_TOOLCHAIN_CMAKE_PATH}/sos-lib.cmake)
