
if( ${SOS_BSP_ARCH} STREQUAL armv7-m )
	set(BUILD_FLOAT ${TOOLCHAIN_FLOAT_DIR_ARMV7M})
	set(BUILD_GCC_LIB gcc)
	set(BUILD_ARCH armv7m)
elseif( ${SOS_BSP_ARCH} STREQUAL armv7e-m )
	set(BUILD_FLOAT ${TOOLCHAIN_FLOAT_DIR_ARMV7EM_FPU})
	set(BUILD_FLOAT_OPTIONS ${TOOLCHAIN_FLOAT_OPTIONS_ARMV7EM_FPU} CACHE INTERNAL "build float options")
	set(BUILD_GCC_LIB gcc-hard)
	set(BUILD_ARCH armv7em_fpu)
endif()

if( ${SOS_BSP_CONFIG} STREQUAL release )
	set(BUILD_TYPE "" CACHE INTERNAL "build type")
	set(BUILD_NAME build_release CACHE INTERNAL "build name")
	set(BUILD_UNDEFINE_SYMBOL symbols_table)
	set(BUILD_HARDWARD_ID ,--defsym=mcu_core_hardware_id=${SOS_BSP_HARDWARD_ID})
elseif( ${SOS_BSP_CONFIG} STREQUAL debug )
	set(BUILD_TYPE "_debug" CACHE INTERNAL "build type")
	set(BUILD_NAME build_debug CACHE INTERNAL "build name")
	set(BUILD_UNDEFINE_SYMBOL symbols_table)
	set(BUILD_HARDWARD_ID ,--defsym=mcu_core_hardware_id=${SOS_BSP_HARDWARD_ID})
elseif( ${SOS_BSP_CONFIG} STREQUAL release_boot )
	set(BUILD_TYPE "" CACHE INTERNAL "build type")
	set(BUILD_NAME build_release_boot CACHE INTERNAL "build name")
	set(SOS_BSP_LIBRARIES ${SOS_BSP_LIBRARIES} -lsos_boot)
	set(BUILD_UNDEFINE_SYMBOL _main)
	set(BUILD_HARDWARD_ID "")
elseif( ${SOS_BSP_CONFIG} STREQUAL debug_boot )
	set(BUILD_TYPE "_debug" CACHE INTERNAL "build type")
	set(BUILD_NAME build_debug_boot CACHE INTERNAL "build name")
	set(BUILD_UNDEFINE_SYMBOL _main)
	set(SOS_BSP_LIBRARIES ${SOS_BSP_LIBRARIES} -lsos_boot_debug)
set(BUILD_HARDWARD_ID "")
endif()

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/${BUILD_NAME} CACHE INTERNAL "runtime output")

file(MAKE_DIRECTORY ${CMAKE_RUNTIME_OUTPUT_DIRECTORY})

if(SOS_BSP_LIBRARIES)
	set(BUILD_LIBRARIES "${SOS_BSP_LIBRARIES} -lsos_sys${BUILD_TYPE} -lsos_mcu_${SOS_BSP_DEVICE_FAMILY}${BUILD_TYPE} -lm -lc -lsos_sys${BUILD_TYPE} -l${BUILD_GCC_LIB}" CACHE INTERNAL "sos build libraries")
else()
	set(BUILD_LIBRARIES "-lsos_sys${BUILD_TYPE} -lsos_mcu_${SOS_BSP_DEVICE_FAMILY}${BUILD_TYPE} -lm -lc -lsos_sys${BUILD_TYPE} -l${BUILD_GCC_LIB}" CACHE INTERNAL "sos build libraries")
endif()
set(BUILD_FLAGS -D__${BUILD_TYPE} -march=${SOS_BSP_ARCH} -DHARDWARE_ID=${SOS_BSP_HARDWARD_ID} -D__${SOS_BSP_DEVICE_FAMILY} -D__${BUILD_ARCH} -D__${SOS_BSP_DEVICE} ${BUILD_FLOAT_OPTIONS} CACHE INTERNAL "sos bsp build options")
set(LINKER_FLAGS "-L${TOOLCHAIN_LIB_DIR}/${SOS_BSP_ARCH}/${BUILD_FLOAT}/. -Wl,-Map,${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${SOS_BSP_NAME}_${SOS_BSP_CONFIG}.map,--gc${BUILD_HARDWARD_ID} -Ttext=${SOS_BSP_START_ADDRESS} -Tldscripts/${SOS_BSP_DEVICE}-rom.ld -nostdlib -u ${BUILD_UNDEFINE_SYMBOL}" CACHE INTERNAL "sos app linker options")

add_executable(${SOS_BSP_NAME}_${SOS_BSP_CONFIG}.elf ${SOS_BSP_SOURCELIST})
add_custom_target(bin_${SOS_BSP_NAME}_${SOS_BSP_CONFIG} DEPENDS ${SOS_BSP_NAME}_${SOS_BSP_CONFIG}.elf COMMAND ${CMAKE_OBJCOPY} -j .text -j .data -O binary ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${SOS_BSP_NAME}_${SOS_BSP_CONFIG}.elf ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${SOS_BSP_NAME}.bin)
add_custom_target(asm_${SOS_BSP_NAME}_${SOS_BSP_CONFIG} DEPENDS bin_${SOS_BSP_NAME}_${SOS_BSP_CONFIG} COMMAND ${CMAKE_OBJDUMP} -S -j .text -j .priv_code -j .data -j .bss -j .sysmem -d ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${SOS_BSP_NAME}_${SOS_BSP_CONFIG}.elf > ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${SOS_BSP_NAME}.S)
add_custom_target(size_${SOS_BSP_CONFIG} DEPENDS asm_${SOS_BSP_NAME}_${SOS_BSP_CONFIG} COMMAND ${CMAKE_SIZE} ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${SOS_BSP_NAME}_${SOS_BSP_CONFIG}.elf)
add_custom_target(${SOS_BSP_CONFIG} ALL DEPENDS size_${SOS_BSP_CONFIG})

target_link_libraries(${SOS_BSP_NAME}_${SOS_BSP_CONFIG}.elf ${BUILD_LIBRARIES})
set_target_properties(${SOS_BSP_NAME}_${SOS_BSP_CONFIG}.elf PROPERTIES LINK_FLAGS ${LINKER_FLAGS})
target_compile_options(${SOS_BSP_NAME}_${SOS_BSP_CONFIG}.elf PUBLIC ${BUILD_FLAGS})
