
if(SOS_BUILD_CONFIG)
	message( STATUS "SOS BUILD CONFIG PROVIDED: " ${SOS_BUILD_CONFIG})
else()
	# See if the director ends in _link or _arm to do the build
	message(STATUS "CMAKE DIRECTORY: " ${CMAKE_BINARY_DIR})
	if( CMAKE_BINARY_DIR MATCHES ".*_link" )
		set(SOS_BUILD_CONFIG link CACHE INTERNAL "sos build config is link")
		message( STATUS "Set build config to link" )
	elseif( CMAKE_BINARY_DIR MATCHES ".*_arm" )
		set(SOS_BUILD_CONFIG arm CACHE INTERNAL "sos build config is arm")
		message( STATUS "Set build config to arm" )
	else()
		message( FATAL_ERROR "No Configuration available build in *_link or *_arm directory or say -DSOS_BUILD_CONFIG:STRING=<arm|link>")
	endif()
endif()
