if(SOS_IS_LINK)
	set(CONFIG_LIST release debug coverage)
	sos_sdk_include_target(StratifyOS ${CONFIG_LIST})
else()
	set(CONFIG_LIST release debug)
	sos_sdk_include_target(StratifyOS_sys ${CONFIG_LIST})
	sos_sdk_include_target(StratifyOS_crt ${CONFIG_LIST})
	sos_sdk_include_target(StratifyOS_boot ${CONFIG_LIST})
endif()
