if(SOS_IS_LINK)
	set(STRATIFYOS_CMAKE_CONFIG_LIST release debug coverage)
	sos_sdk_include_target(StratifyOS "${STRATIFYOS_CMAKE_CONFIG_LIST}")
else()
	set(STRATIFYOS_CMAKE_CONFIG_LIST release debug)
	sos_sdk_include_target(StratifyOS_sys "${STRATIFYOS_CMAKE_CONFIG_LIST}")
	sos_sdk_include_target(StratifyOS_crt "${STRATIFYOS_CMAKE_CONFIG_LIST}")
	sos_sdk_include_target(StratifyOS_boot "${STRATIFYOS_CMAKE_CONFIG_LIST}")
endif()
